<?php
function ensureSessionStarted(){ if(session_status() !== PHP_SESSION_ACTIVE){ session_start(); } }
function getUsersFilePath(){ return dirname(__DIR__) . DIRECTORY_SEPARATOR . 'users.txt'; }
function sanitizeEmail($email){ $email = trim(strtolower($email)); return filter_var($email, FILTER_VALIDATE_EMAIL) ? $email : ''; }
function sanitizePlate($plate){ $plate = strtoupper(trim($plate)); $plate = preg_replace('/[^A-Z0-9-]/','',$plate); return $plate; }
function userExists($email){ $email = sanitizeEmail($email); if($email==='') return false; $path = getUsersFilePath(); if(!file_exists($path)) return false; $fh = fopen($path,'r'); if(!$fh) return false; while(($line = fgets($fh)) !== false){ $parts = explode('|', trim($line)); if(isset($parts[0]) && $parts[0] === $email){ fclose($fh); return true; } } fclose($fh); return false; }
function createUser($email, $name='', $plate=''){ $email = sanitizeEmail($email); if($email==='') return false; if(userExists($email)) return true; $safeName = str_replace(['|',"\n","\r"],' ', trim($name)); $safePlate = str_replace(['|',"\n","\r"],' ', sanitizePlate($plate)); $line = $email . '|' . date('c') . '|' . $safeName . '|' . $safePlate . PHP_EOL; return (bool) file_put_contents(getUsersFilePath(), $line, FILE_APPEND); }
function updateUserName($email, $name){ $email = sanitizeEmail($email); if($email==='') return false; $path = getUsersFilePath(); if(!file_exists($path)) return false; $lines = file($path, FILE_IGNORE_NEW_LINES); $updated = false; foreach($lines as &$line){ $parts = explode('|',$line); if(isset($parts[0]) && $parts[0] === $email){ $parts[2] = str_replace(['|',"\n","\r"],' ', trim($name)); $line = implode('|',$parts); $updated = true; break; } } if($updated){ file_put_contents($path, implode(PHP_EOL,$lines) . PHP_EOL); } return $updated; }
function updateUserPlate($email, $plate){ $email = sanitizeEmail($email); if($email==='') return false; $path = getUsersFilePath(); if(!file_exists($path)) return false; $lines = file($path, FILE_IGNORE_NEW_LINES); $updated = false; foreach($lines as &$line){ $parts = explode('|',$line); if(isset($parts[0]) && $parts[0] === $email){ $parts[3] = str_replace(['|',"\n","\r"],' ', sanitizePlate($plate)); $line = implode('|',$parts); $updated = true; break; } } if($updated){ file_put_contents($path, implode(PHP_EOL,$lines) . PHP_EOL); } return $updated; }
function getUserProfile($email){ $email = sanitizeEmail($email); if($email==='') return null; $path = getUsersFilePath(); if(!file_exists($path)) return null; $fh = fopen($path,'r'); if(!$fh) return null; while(($line = fgets($fh)) !== false){ $parts = explode('|', trim($line)); if(isset($parts[0]) && $parts[0] === $email){ fclose($fh); return [ 'email'=>$parts[0], 'createdAt'=>$parts[1] ?? '', 'name'=>$parts[2] ?? '', 'plate'=>$parts[3] ?? '' ]; } } fclose($fh); return null; }
function findUserByPlate($plate){ $plate = sanitizePlate($plate); if($plate==='') return null; $path = getUsersFilePath(); if(!file_exists($path)) return null; $fh = fopen($path,'r'); if(!$fh) return null; while(($line = fgets($fh)) !== false){ $parts = explode('|', trim($line)); if(isset($parts[3]) && $parts[3] === $plate){ fclose($fh); return [ 'email'=>$parts[0] ?? '', 'createdAt'=>$parts[1] ?? '', 'name'=>$parts[2] ?? '', 'plate'=>$parts[3] ?? '' ]; } } fclose($fh); return null; }
function loginUser($email){ ensureSessionStarted(); $_SESSION['user_email'] = sanitizeEmail($email); if(function_exists('session_regenerate_id')){ @session_regenerate_id(true); } }
function logoutUser(){ ensureSessionStarted(); unset($_SESSION['user_email']); }
function getCurrentUserEmail(){ ensureSessionStarted(); return $_SESSION['user_email'] ?? ''; }
function requireAuthOrRedirect(){ ensureSessionStarted(); if(empty($_SESSION['user_email'])){ $target = basename(parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH)); $qs = $_SERVER['QUERY_STRING'] ?? ''; $redir = $target . ($qs ? ('?' . $qs) : ''); header('Location: signin.php?redirect=' . urlencode($redir)); exit; } }
?>

